
snowflake:
  target: main
  outputs:
    main:
      type: snowflake
      account: fda51850
      threads: 5
      client_session_keep_alive: false

      # Your Snowflake username
      user: opsadmin
      password: "Xvrkt4R3qtE7AmAf"
      authenticator: username_password_mfa
      role: DATA_SUPPORT
      database: SNOWFLAKE
      schema: RANAA_MAHVEEN
      warehouse: DATA_TOOLS_WH
